apiVersion: v1
kind: Service
metadata:
  name: pv-cleaner-operator
  namespace: giantswarm
  labels:
    app: pv-cleaner-operator
spec:
  ports:
  - port: 8000
  selector:
    app: pv-cleaner-operator
